import { PrismaClient, VariantLevel } from '@prisma/client';

interface CsvRow {
  productName: string;
  productCode: string;
  productFamily: string;
  variant1Family: string;
  variant1Name: string;
  variant1Code: string;
  variant2Family: string;
  variant2Name: string;
  variant2Code: string;
}

interface VariantDefinition {
  familyName: string;
  name: string;
  code: string;
  level: VariantLevel;
}

const RAW_CSV = `PRODUIT;CODE;FAMILLE PRODUIT;;FAMILLE PRODUIT;VARIANTE 1;CODE;;FAMILLE PRODUIT;VARIANTE 2;CODE
ACCESSOIRE;CB;ACCESSOIRE BMS;;ACCESSOIRE BMS;SANS VARIANTE;0;;ACCESSOIRE BMS;SANS VARIANTE;0
AUTOMATE PROGRAMMABLE;AU;ACCESSOIRE BMS;;ALIMENTATION ELECTRIQUE;SANS VARIANTE;0;;ALIMENTATION ELECTRIQUE;SANS VARIANTE;0
BORNIER;BN;ACCESSOIRE BMS;;ALIMENTATION ELECTRIQUE;TRANSFORMATEUR;T;;ALIMENTATION ELECTRIQUE;TRANSFORMATEUR;T
CARTE;CT;ACCESSOIRE BMS;;ANCRAGE;SANS VARIANTE;0;;ANCRAGE;SANS VARIANTE;0
ECRAN;TV;ACCESSOIRE BMS;;BOBINE ELECTRIQUE;SANS VARIANTE;0;;BOBINE ELECTRIQUE;SANS VARIANTE;0
EXTENSION RACK;ER;ACCESSOIRE BMS;;CABLE;SANS VARIANTE;0;;CABLE;SANS VARIANTE;0
HUB TELECOMMUNICATION;HT;ACCESSOIRE BMS;;CHAUDIERE;SANS VARIANTE;0;;CLAPET ANTI RETOUR;SANS VARIANTE;0
LICENCE LOGICIEL;LL;ACCESSOIRE BMS;;CLAPET ANTI RETOUR;CLAPET A DISQUE;1;;COFFRET ELECTRIQUE;SANS VARIANTE;0
MODULE TELECOMMUNICATION;MT;ACCESSOIRE BMS;;CLAPET ANTI RETOUR;CLAPET A BILLE;2;;COLLE;SANS VARIANTE;0
RELAIS;RL;ACCESSOIRE BMS;;CLAPET ANTI RETOUR;CLAPET A BATTANT;3;;COMPENSATEUR;SANS VARIANTE;0
ALIMENTATION ELECTRIQUE;AE;ALIMENTATION ELECTRIQUE;;COFFRET ELECTRIQUE;SANS VARIANTE;0;;COMPOSANT ELECTRONIQUE;SANS VARIANTE;0
ANCRAGE;AG;ANCRAGE;;COFFRET ELECTRIQUE;ACCESSOIRE DE CABLAGE;A;;CONNECTEUR ELEC. RAPIDE;SANS VARIANTE;0
BOBINE ELECTRIQUE;AC;BOBINE ELECTRIQUE;;COLLE;SANS VARIANTE;0;;CONNECTEUR ELEC. RAPIDE;SANS VARIANTE;0
CABLE ELECTRIQUE;CA;CABLE;;COMPENSATEUR;A BRIDE;1;;CONNECTEUR ELECTRIQUE;CONNECTEUR DROIT;D
CABLE MECANIQUE;AB;CABLE;;COMPENSATEUR;A SOUDER;2;;CONNECTEUR ELECTRIQUE;CONNECTEUR CIRCULAIRE;C
CHAUDIERE;CH;CHAUDIERE;;COMPOSANT ELECTRONIQUE;SANS VARIANTE;0;;CONNECTEUR ELECTRIQUE;SANS VARIANTE;0
CLAPET ANTI RETOUR;AA;CLAPET ANTI RETOUR;;CONNECTEUR ELEC. RAPIDE;AVEC ISOLANT;I;;DEBITMETRE A ROUE;ENTRE-BRIDE;E
COFFRET ELECTRIQUE;CO;COFFRET ELECTRIQUE;;CONNECTEUR ELEC. RAPIDE;MALE/FEMELLE;M;;DEBITMETRE A ROUE;A BRIDE;A
COLLE;CL;COLLE;;CONNECTEUR ELECTRIQUE;EMBASE;E;;DEBITMETRE A ROUE;FILETE;F
FREIN FILET;FF;COLLE;;CONNECTEUR ELECTRIQUE;FICHE / CONNECTEUR;F;;DEBITMETRE A TRANSMETTEUR;ENTRE-BRIDE;E
MASTIC;MA;COLLE;;CONNECTEUR ELECTRIQUE;SANS VARIANTE;0;;DEBITMETRE A TRANSMETTEUR;A BRIDE;A
COMPENSATEUR;CP;COMPENSATEUR;;CONNECTEUR ELECTRIQUE;CONTACT DE CONNECTEURS;C;;DEBITMETRE A TRANSMETTEUR;FILETE;F
SEMI-CONDUCTEUR;SC;COMPOSANT ELECTRONIQUE;;CONNECTEUR ELECTRIQUE;BORNIER;B;;DETECTEUR;SANS VARIANTE;0
FICHE BANANE;FB;CONNECTEUR ELEC. RAPIDE;;CONNECTEUR ELECTRIQUE;CONNECTEUR PRE-CABLE;P;;DETENDEUR;A BRIDE;A
PINCE CROCODILE;PC;CONNECTEUR ELEC. RAPIDE;;CONNECTEUR ELECTRIQUE;A BOULE;A;;DETENDEUR;SW;S
CONNECTEUR ELECTRIQUE;CE;CONNECTEUR ELECTRIQUE;;DEBITMETRE A ROUE;SANS VARIANTE;0;;DETENDEUR;BW;B
DEBITMETRE (TYPE KOBOLD);DR;DEBITMETRE A ROUE;;DEBITMETRE A TRANSMETTEUR;1 TETE;1;;DETENDEUR;FILETE;F
DEBITMETRE MASSIQUE;DM;DEBITMETRE A TRANSMETTEUR;;DEBITMETRE A TRANSMETTEUR;2 TETES;2;;DETENDEUR;ENTRE-BRIDE;E
DEBITMETRE VORTEX;DV;DEBITMETRE A TRANSMETTEUR;;DETECTEUR;SANS VARIANTE;0;;DOIGT DE GANT;NPTM;A
CAPTEUR O2;DO;DETECTEUR;;DETECTEUR;DETECTEUR UV;U;;DOIGT DE GANT;NPTF;B
CELLULE DETECTION FLAMME;DF;DETECTEUR;;DETECTEUR;DETECTEUR IR;I;;DOIGT DE GANT;GAZM;C
DETECTEUR INDUCTIF;DT;DETECTEUR;;DETECTEUR;CAPTEUR PYROMETRIQUE;P;;DOIGT DE GANT;GAZF;D
DETENDEUR;DE;DETENDEUR;;DETECTEUR;DETECTEUR O2;D;;DOIGT DE GANT;SANS VARIANTE;0
DOIGT DE GANT;DG;DOIGT DE GANT;;DETECTEUR;INDUCTIF;A;;ELECTRODE;SANS VARIANTE;0
BOUGIE;BO;ELECTRODE;;DETENDEUR;AVEC CLAPET DE SECURITE;A;;ELECTRODE DE SOUDURE;SANS VARIANTE;0
ELECTRODE DE COMBUSTION;EC;ELECTRODE;;DETENDEUR;SANS CLAPET DE SECURITE;S;;ELECTROVANNE;SANS VARIANTE;0
ISOLATEUR CERAMIQUE (ELECTRODE);IC;ELECTRODE;;DOIGT DE GANT;GAZ;G;;FILTRE;SANS VARIANTE;0
ELECTRODE DE SOUDURE;EL;ELECTRODE DE SOUDURE;;DOIGT DE GANT;AIR;A;;FLEXIBLE;SANS VARIANTE;0
ELECTROVANNE;EV;ELECTROVANNE;;DOIGT DE GANT;FIOUL LOURD;L;;FLEXIBLE;A BRIDE;B
FIL ELECTRIQUE;FI;FIL;;DOIGT DE GANT;FIOUL DOMESTIQUE;D;;FLEXIBLE;BW;S
FILTRE A PANIER DUPLEX FIOUL;FD;FILTRE;;DOIGT DE GANT;SANS VARIANTE;0;;FLEXIBLE;FILETE;F
FILTRE A PANIER POSTE DE DETENTE;FG;FILTRE;;ELECTRODE;ALLUMAGE;A;;FLEXIBLE;BRIDE+FILETE;C
FILTRE A PANIER SIMPLEX FIOUL;FS;FILTRE;;ELECTRODE;IONISATION;I;;FLEXIBLE;BRIDE+BW;D
FILTRE AUTO-NETTOYANT;FN;FILTRE;;ELECTRODE;SANS VARIANTE;0;;FLEXIBLE;FILETE+BW;E
FILTRE RAMPE AIR;FA;FILTRE;;ELECTRODE;ISOLATION SEULE;S;;JOINT;SANS VARIANTE;0
FILTRE Y;FY;FILTRE;;ELECTRODE;CONNECTEUR ELECTRODE;C;;JOINT;SANS VARIANTE;0
TAMIS;TA;FILTRE;;ELECTRODE;ALLUMAGE OU IONISATION;B;;MANOMETRE;SANS VARIANTE;0
FLEXIBLE CAOUTCHOUC;FC;FLEXIBLE;;ELECTRODE;ALLUMAGE ET IONISATION;D;;MATERIEL HYDRAULIQUE;SANS VARIANTE;0
FLEXIBLE CERAMIQUE;FR;FLEXIBLE;;ELECTRODE DE SOUDURE;INOX;I;;OPTIQUE;SANS VARIANTE;0
FLEXIBLE INOX;FL;FLEXIBLE;;ELECTRODE DE SOUDURE;ACIER;A;;OUTIL;SANS VARIANTE;0
FLEXIBLE PLASTIQUE;FP;FLEXIBLE;;ELECTROVANNE;SANS VARIANTE;0;;POMPE;FIOUL LOURD;L
GAINE THERMORETRACTABLE;GT;GAINES THERMO;;FIL;SANS VARIANTE;0;;POMPE;FIOUL DOMESTIQUE;D
JOINT;JN;JOINT;;FILTRE;SANS VARIANTE;0;;POMPE;FLUIDE THERMIQUE;T
MANOMETRE;MN;MANOMETRE;;FLEXIBLE;ONDULEUX INOX;O;;POMPE;SANS VARIANTE;0
DIVISEUR DE DEBIT;DB;MATERIEL HYDRAULIQUE;;FLEXIBLE;CERAMIC;C;;PRESSE-ETOUPE;SANS VARIANTE;0
MOTO-REDUCTEUR;MR;MOTO-REDUCTEURS;;FLEXIBLE;CAOUTCHOUC;A;;RACCORD MECANIQUE;SANS VARIANTE;0
MIROIR;MI;OPTIQUE;;FLEXIBLE;SANS VARIANTE;0;;SERVOMOTEUR;SANS VARIANTE;0
PROJECTEUR OPTIQUE;PO;OPTIQUE;;GAINES THERMO;SANS VARIANTE;0;;SOUFFLE;SANS VARIANTE;0
CLE DYNAMOMETRIQUE;CY;OUTIL;;JOINT;TORIQUE;T;;TAMIS;SANS VARIANTE;0
POMPE A MAIN;PM;POMPE;;JOINT;PLAT;P;;THERMOMETRE;SANS VARIANTE;0
POMPE A PALETTE;PP;POMPE;;JOINT;EN V;V;;THERMOSTAT;SANS VARIANTE;0
POMPE A VIS;PV;POMPE;;JOINT;A LEVRE;L;;TRANSMETTEUR DE PRESSION;SANS VARIANTE;0
PRESSE-ETOUPE;PE;PRESSE-ETOUPE;;JOINT;BAGUE BS;B;;TRANSMETTEUR DE TEMPERATURE;SANS VARIANTE;0
COUDE;CD;RACCORD MECANIQUE;;JOINT;SANS VARIANTE;0;;TUBE;SANS VARIANTE;0
CROIX;CX;RACCORD MECANIQUE;;JOINT;METALLOPLASTIQUE;M;;TUBES PLASTIQUES;SANS VARIANTE;0
MAMELON;MM;RACCORD MECANIQUE;;JOINT;CUIVRE;C;;VANNE AUTOMATIQUE;SANS VARIANTE;0
MANCHON;MC;RACCORD MECANIQUE;;MANOMETRE;SANS VARIANTE;0;;VANNE AUTOMATIQUE;ENTRE-BRIDE;E
RACCORD CANELE;RC;RACCORD MECANIQUE;;MATERIEL HYDRAULIQUE;SANS VARIANTE;0;;VANNE AUTOMATIQUE;A BRIDE;A
RACCORD FILETE;RF;RACCORD MECANIQUE;;MOTO-REDUCTEURS;SANS VARIANTE;0;;VANNE AUTOMATIQUE;SW;S
REDUCTION;RD;RACCORD MECANIQUE;;OPTIQUE;MIROIR DE PREMIERE SURFACE;P;;VANNE AUTOMATIQUE;BW;B
TE;TE;RACCORD MECANIQUE;;OPTIQUE;SANS VARIANTE;0;;VANNE AUTOMATIQUE;FILETE;F
RACCORD RAPIDE;RR;RACCORD RAPIDE;;OUTIL;SANS VARIANTE;0;;VANNE MANUELLE;SANS VARIANTE;0
RECHAUFFEUR;RE;RECHAUFFEUR;;POMPE;SANS VARIANTE;0;;VANNE MANUELLE;ENTRE-BRIDE;E
RESSORT;RS;RESSORT;;POMPE;VOLUMETRIQUE;V;;VANNE MANUELLE;A BRIDE;A
SERVOMOTEUR;SE;SERVOMOTEUR;;POMPE;CENTRIFUGE;C;;VANNE MANUELLE;SW;S
SOUFFLE;SO;SOUFFLE;;POMPE;A MAIN;M;;VANNE MANUELLE;BW;B
THERMOMETRE;TM;THERMOMETRE;;PRESSE-ETOUPE;PRESSE-ETOUPE;P;;VANNE MANUELLE;FILETE;F
THERMOSTAT;TS;THERMOSTAT;;PRESSE-ETOUPE;JOINT DE PE;J;;VENTILATEUR;SANS CALO, SANS INSONORISATION;0
TRANSMETTEUR DE PRESSION;TP;TRANSMETTEUR;;PRESSE-ETOUPE;ECROU DE PE;E;;VENTILATEUR;CALORIFUGE;C
TRANSMETTEUR DE TEMPERATURE;TT;TRANSMETTEUR;;PRESSE-ETOUPE;RONDELLE DE PE;R;;VENTILATEUR;INSONORISATION;I
TUBE;TU;TUBE;;PRESSE-ETOUPE;BOUCHON DE PE;B;;VENTILATEUR NANOX COMPACT;SANS INSONORISATION;0
VANNE A SOUPAPE AUTO;VF;VANNE;;RACCORD MECANIQUE;SANS VARIANTE;0;;VENTILATEUR NANOX COMPACT;CALORIFUGE;C
VANNE BS AUTO;VC;VANNE;;RACCORD MECANIQUE;UNION;U;;VENTILATEUR NANOX COMPACT;INSONORISATION;I
VANNE PAPILLON;VD;VANNE;;RACCORD RAPIDE;SANS VARIANTE;0;;VERIN;SANS VARIANTE;0
MANIFOLD;AF;VANNE;;RACCORD RAPIDE;PRISE DE PRESSION;A;;VERRE;SANS VARIANTE;0
VANNE OPERCULE;VO;VANNE;;RECHAUFFEUR;SANS VARIANTE;0;;VANNE;DN08;A
VANNE POINTEAU;VT;VANNE;;SERVOMOTEUR;SANS VARIANTE;0;;VANNE;DN10;B
VANNE SOUPAPE;VS;VANNE;;SOUFFLE;SANS VARIANTE;0;;VANNE;DN15;C
VANNE BS;VB;VANNE;;TAMIS;SANS VARIANTE;0;;VANNE;DN20;D
VANNE GUILLOTINE;VG;VANNE;;THERMOMETRE;SANS VARIANTE;0;;VANNE;DN25;E
VANNE PAPILLON;VP;VANNE;;THERMOSTAT;SANS VARIANTE;0;;VANNE;DN40;F
VANNE SOUPAPE CLAPET PARABOLIQUE;VI;VANNE;;TRANSMETTEUR DE PRESSION;SANS VARIANTE;0;;VANNE;DN50;G
VANNE SOUPAPE A SOUFFLET;VJ;VANNE;;TRANSMETTEUR DE TEMPERATURE;SANS VARIANTE;0;;VANNE;DN80;H
VENTILATEUR AIR PRIMAIRE;AP;VENTILATEUR;;TUBE;SANS VARIANTE;0;;VANNE;DN100;I
VENTILATEUR AIR SECONDAIRE;AS;VENTILATEUR;;VANNE AUTOMATIQUE;SANS VARIANTE;0;;VANNE;DN150;J
VENTILATEUR DE DILUTION;AD;VENTILATEUR;;VANNE AUTOMATIQUE;AVEC FIN DE COURSE;F;;VANNE;DN200;K
VENTILATEUR DE SECOURS;AR;VENTILATEUR;;VANNE AUTOMATIQUE;SANS FIN DE COURSE;S;;VANNE;DN250;L
VENTILATEUR NANOX COMPACT;AN;VENTILATEUR NANOX COMPACT;;VANNE MANUELLE;SANS VARIANTE;0;;VANNE;DN300;M
VERIN HYDRAULIQUE;VH;VERIN;;VANNE MANUELLE;AVEC FIN DE COURSE;F;;VANNE;DN350;N
VERIN MECANIQUE;VM;VERIN;;VANNE MANUELLE;SANS FIN DE COURSE;S;;VANNE;DN400;O
VERIN PNEUMATIQUE;VA;VERIN;;VENTILATEUR;AVEC SILENCIEUX;S;;VANNE;DN450;P
VERRE;VE;VERRE;;VENTILATEUR;NU;0;;VANNE;DN500;Q
;;;;VENTILATEUR NANOX COMPACT;TAILLE 1 GAUCHE;1;;VANNE;DN600;R
;;;;VENTILATEUR NANOX COMPACT;TAILLE 1 DROITE;2;;VANNE;DN32;S
;;;;VENTILATEUR NANOX COMPACT;TAILLE 2 GAUCHE;3;;VANNE;DN65;T
;;;;VENTILATEUR NANOX COMPACT;TAILLE 2 DROITE;4;;VANNE;DN125;U
;;;;VENTILATEUR NANOX COMPACT;TAILLE 3 GAUCHE;5;;;;
;;;;VENTILATEUR NANOX COMPACT;TAILLE 3 DROITE;6;;;;
;;;;VERIN;SANS VARIANTE;0;;;;
;;;;VERRE;SANS VARIANTE;0;;;;
;;;;VANNE;AUTOMATIQUE;A;;;;
;;;;VANNE;MANUEL;M;;;;
;;;;;;;;;;`;
const prisma = new PrismaClient();

const clean = (value?: string) => (value ?? '').replace(/\s+/g, ' ').trim();

function parseRawCsv(): CsvRow[] {
  return RAW_CSV.trim()
    .split(/\r?\n/)
    .slice(1)
    .map((line) => line.split(';'))
    .map((cells) => {
      while (cells.length < 11) {
        cells.push('');
      }

      const [
        productName,
        productCode,
        productFamily,
        _,
        rawVariant1Family,
        variant1Name,
        variant1Code,
        __,
        rawVariant2Family,
        variant2Name,
        variant2Code,
      ] = cells;

      const sanitizedProductFamily = clean(productFamily);
      return {
        productName: clean(productName),
        productCode: clean(productCode),
        productFamily: sanitizedProductFamily,
        variant1Family: clean(rawVariant1Family) || sanitizedProductFamily,
        variant1Name: clean(variant1Name),
        variant1Code: clean(variant1Code),
        variant2Family: clean(rawVariant2Family) || sanitizedProductFamily,
        variant2Name: clean(variant2Name),
        variant2Code: clean(variant2Code),
      };
    })
    .filter((row) =>
      Object.values(row).some((value) => value && value.length > 0),
    );
}

async function main() {
  console.log('🌱 Starting seeding...');

  const rows = parseRawCsv();

  const familyCache = new Map<string, string>();
  async function getFamilyId(name: string) {
    const normalized = clean(name);
    if (!normalized) {
      throw new Error('Nom de famille manquant dans le CSV');
    }
    if (familyCache.has(normalized)) {
      return familyCache.get(normalized)!;
    }
    let family = await prisma.family.findFirst({ where: { name: normalized } });
    if (!family) {
      family = await prisma.family.create({ data: { name: normalized } });
    }
    familyCache.set(normalized, family.id);
    return family.id;
  }

  const variantCache = new Set<string>();
  async function createVariant(def: VariantDefinition) {
    const familyId = await getFamilyId(def.familyName);
    const cacheKey = `${familyId}:${def.code || def.name}:${def.level}`;
    if (variantCache.has(cacheKey)) return;

    const code = clean(def.code) || '0';
    const name = clean(def.name) || 'Sans variante';

    await prisma.variant.upsert({
      where: {
        familyId_code_variantLevel: {
          familyId,
          code,
          variantLevel: def.level,
        },
      },
      update: {
        name,
      },
      create: {
        familyId,
        name,
        code,
        variantLevel: def.level,
      },
    });

    variantCache.add(cacheKey);
  }

  const productTypeCommerce = await prisma.productType.upsert({
    where: { code: 'C' },
    update: {},
    create: {
      name: 'Commerce',
      code: 'C',
    },
  });

  console.log('✅ Product type Commerce created');

  // Créer toutes les familles présentes dans le CSV
  for (const row of rows) {
    if (row.productFamily) await getFamilyId(row.productFamily);
    if (row.variant1Family) await getFamilyId(row.variant1Family);
    if (row.variant2Family) await getFamilyId(row.variant2Family);
  }
  console.log('✅ Families created/updated');

  // Créer les variantes pour les deux niveaux
  for (const row of rows) {
    if (row.variant1Name) {
      await createVariant({
        familyName: row.variant1Family,
        name: row.variant1Name,
        code: row.variant1Code || '0',
        level: 'FIRST',
      });
    }
    if (row.variant2Name) {
      await createVariant({
        familyName: row.variant2Family,
        name: row.variant2Name,
        code: row.variant2Code || '0',
        level: 'SECOND',
      });
    }
  }
  console.log('✅ Variants created/updated');

  const createdProducts = new Set<string>();
  for (const row of rows) {
    if (
      !row.productCode ||
      !row.productName ||
      !row.productFamily ||
      createdProducts.has(row.productCode)
    ) {
      continue;
    }
    const familyId = await getFamilyId(row.productFamily);
    await prisma.product.upsert({
      where: { code: row.productCode },
      update: {
        name: row.productName,
        familyId,
        productTypeId: productTypeCommerce.id,
      },
      create: {
        name: row.productName,
        code: row.productCode,
        familyId,
        productTypeId: productTypeCommerce.id,
      },
    });
    createdProducts.add(row.productCode);
  }

  console.log(`✅ ${createdProducts.size} products created/updated`);
  console.log('🌱 Seeding finished!');
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

